[theme]
base="light"
backgroundColor="white"
secondaryBackgroundColor="lavender"
codeBackgroundColor="powderBlue"
font = "sans-serif"

[theme.sidebar]
backgroundColor="ghostWhite"
secondaryBackgroundColor="lavender"